server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  profile:
    active: dev
  datasource:
  password:
  url: jdbc:postgresql://localhost:5432/AuthData
  username:
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect